### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by byteboy-dev** [fenglh/OCOBfuscatorAPP#2]
下载的文件里没有dmg文件了

**Comment by fenglh** [comment]
> 下载的文件里没有dmg文件了

上个版本有些bug，正在修复，修复好了会马上上传

**Comment by byteboy-dev** [comment]
ITX <notifications@github.com>于2020年10月23日 周五17:15写道：

**Comment by byteboy-dev** [comment]
> 下载的文件里没有dmg文件了



> > 下载的文件里没有dmg文件了
> 
> 上个版本有些bug，正在修复，修复好了会马上上传

好的 多谢！上个版本的一个问题是用xcode12编译的时候会经常报 normal i386_x64 这样的错误

**Comment by fenglh** [comment]
> > 下载的文件里没有dmg文件了
> 
> > > 下载的文件里没有dmg文件了
> > 
> > 
> > 上个版本有些bug，正在修复，修复好了会马上上传
> 
> 好的 多谢！上个版本的一个问题是用xcode12编译的时候会经常报 normal i386_x64 这样的错误

好的，我看看

**Comment by fenglh** [comment]
> 下载的文件里没有dmg文件了

已更新dmg啦
